[project]
name = 'jsharpe'
version = "0.0.0"
description = "Sharpe ratio"
# Please add authors and correct the email...
authors = [{name='tschm', email='tschm@mailinator.com'}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
]

[project.urls]
repository = "https://github.com/tschm/jsharpe"

[project.optional-dependencies]
dev = [
    "pytest-cov>=6.0.0",
    "pytest>=8.3.3",
    "pre-commit>=4.0.1",
    "marimo==0.13.15",
    "numpy==2.3.0",
    "matplotlib==3.10.0",
    "altair==6.0.0",
    "vega-datasets==0.9.0",
    "pyarrow",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/jsharpe"]

[tool.hatch.build]
include = [
    "LICENSE",    # Ensure the LICENSE file is included in your package
    "README.md",
    "src/jsharpe"
]

[tool.bandit]
exclude_dirs = ["tests"]

[tool.deptry]
# see https://deptry.com/usage/#pep-621-dev-dependency-groups
pep621_dev_dependency_groups = ["dev"]
