[project]
name = 'jsharpe'
version = "0.1.0"
description = "Sharpe ratio"
authors = [{name='Thomas Schmelzer', email='thomas@jqr.ae'}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.0",
    "scipy>=1.16.3"
]
license = { file="LICENSE" }
keywords = ["Sharpe ratio", "quant", "risk", "statistics"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Mathematics",
]

[project.urls]
repository = "https://github.com/tschm/jsharpe"

[project.optional-dependencies]
dev = [
    "pytest-cov>=7.0.0",
    "pytest>=9.0.1",
    "pytest-html>=4.1.1",
    "pre-commit>=4.0.1",
    "marimo==0.18.3",
    "cvxpy>=1.7.0",
    "pdoc>=16.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/jsharpe"]

[tool.hatch.build]
include = [
    "LICENSE",    # Ensure the LICENSE file is included in your package
    "README.md",
    "src/jsharpe"
]

[tool.deptry]
# see https://deptry.com/usage/#pep-621-dev-dependency-groups
pep621_dev_dependency_groups = ["dev"]

