[project]
name = "jsharpe"
version = "0.2.0"
description = "Probabilistic Sharpe ratio and related statistics."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

authors = [
    { name = "Thomas Schmelzer", email = "thomas@jqr.ae" }
]

keywords = ["Sharpe ratio", "quant", "risk", "statistics"]
dependencies = [
    "numpy>=2.3.0",
    "scipy>=1.16.3",
]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Mathematics",
]

[project.urls]
repository = "https://github.com/tschm/jsharpe"
homepage = "https://github.com/tschm/jsharpe"
issues = "https://github.com/tschm/jsharpe/issues"

[project.optional-dependencies]
dev = [
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "pytest-html>=4.1.1",
    "pre-commit>=4.0.1",
    "marimo==0.18.4",
    "cvxpy>=1.7.0",
    "pdoc>=16.0.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["LICENSE", "README.md"]

[tool.hatch.build.targets.wheel]
#package-dir = "src"
package = ["src/jsharpe"]

[tool.deptry]
pep621_dev_dependency_groups = ["dev"]

# --- uv integration ---------------------------------------------------------
[tool.uv.sources]
jsharpe = { path = ".", editable = true }
